ams_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from ams_app import views

urlpatterns = [
    url(r'^assignments/$', views.create_assignment, name='add_assignment'),
    url(r'^assignments/(?P<id>[-\w]+)/pass$', views.pre_submission,
        name='pre_submission'),
    url(r'^assignments/(?P<id>[-\w]+)/submission$', views.submit_assignment,
        name='assignment_submission'),
    url(r'^assignments/(?P<id>[-\w]+)/submissions$', views.assignment_submissions,
        name='submissions'),
    url(r'^assignments/(?P<id>[-\w]+)/$', views.assignment_detail,
        name='assignment_detail'),
    url(r'^assignments/(?P<id>[-\w]+)/delete$', views.delete_assignment,
        name='delete_assignment'),
    url(r'^assignments/(?P<id>[-\w]+)/edit$', views.edit_assignment,
        name='edit_assignment'),
    url(r'^submissions/(?P<id>[-\w]+)/delete$', views.delete_submission,
        name='delete_submission'),
    url(r'^submissions/(?P<id>[-\w]+)/edit$', views.edit_submission,
        name='submission_detail'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    # django auth urls
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^login$', views.login_user, name='login'),
    url(r'^logout$', views.logout_user, name='logout'),
    url(r'^$', views.sign_up),
]

django_ams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("ams_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ams_app/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


def unique_passcode():
    d = uuid.uuid4()
    passcode = d.hex
    return passcode[0:8]


class Profile(models.Model):
    role_choice = (('Lecturer', 'Lecturer'), ('Student', 'Student'))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=100, choices=role_choice, default='Lecturer')
    matric_number = models.CharField(max_length=12, unique=True, blank=True, null=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Assignment(models.Model):
    title = models.CharField(max_length=255)
    passcode = models.CharField(max_length=100, default=unique_passcode)
    upload = models.FileField(upload_to='assignments/', null=True, default="No file uploaded")
    due_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    course_code = models.CharField(max_length=8)
    course_title = models.CharField(max_length=255)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='assignments'
    )


class Submission(models.Model):
    matric_number = models.CharField(max_length=100)
    upload = models.FileField(upload_to='submissions/')
    submitted_at = models.DateField(auto_now=True)
    last_updated = models.DateField(auto_now=True)
    assignment = models.ForeignKey(
        'Assignment',
        on_delete=models.CASCADE,
        related_name='submissions'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='submissions'
    )
    grade = models.CharField(max_length=100, null=True, blank=True, default="No grade yet")
    feedback = models.CharField(max_length=255, null=True, blank=True, default="No feedback yet")

ams_app/forms.py
from django.forms import ModelForm
from ams_app import models
from django.contrib.auth.models import User
from django import forms
 

class UserForm(ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
            'label': 'username'
        }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        help_texts = {
            'username': '',
        }
        widgets = {
            'password' : forms.PasswordInput()
        }

CHOICES = (
   ('Lecturer', 'Lecturer'), 
   ('Student', 'Student'),
)


class ProfileForm(ModelForm):
    role = forms.ChoiceField(
        choices=CHOICES,
        widget=forms.Select(attrs={'class':'form-control'}),
        label='I am a...',
    )
    
    class Meta:
        model = models.Profile
        fields = ['role', 'matric_number']

        
class AssignmentForm(ModelForm):
    upload = forms.FileField(
        required=False,
        label='Select a file',
        help_text='max. 42 megabytes'
    )
    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'datepicker'})
    )

    class Meta:
        model = models.Assignment
        fields = ['title', 'upload', 'due_date', 'course_code', 'course_title']


class SubmissionForm(ModelForm):
    upload = forms.FileField(required=True)

    class Meta:
        model = models.Submission
        fields = ['upload']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        fields = ['username', 'password']
        help_texts = {
            'username': '',
        }


class PassForm(forms.Form):
    passcode = forms.CharField()

    class Meta:
        fields = "passcode"


class AssignmentSearchForm(forms.Form):
    q = forms.CharField()

    class Meta:
        fields = "q"
        errorlist = {
            'q': '',
        }


class SubmissionSearchForm(forms.Form):
    q = forms.CharField()

    class Meta:
        fields = "q"


class GradeForm(forms.Form):
    grade = forms.CharField()

    class Meta:
        fields = ['grade']


class FeedbackForm(forms.Form):
    feedback = forms.CharField()
    
    class Meta:
        fields = ['feedback']

ams_app/views.py
import os

import datetime
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector, SearchQuery

from ams_app import forms
from ams_app.models import Assignment, Submission, Profile


def sign_up(request):
    user_form = forms.UserForm(request.POST or None)
    profile_form = forms.ProfileForm(request.POST or None)
    if request.method == "POST":
        if user_form.is_valid() and profile_form.is_valid():
            username=user_form.cleaned_data["username"]
            email=user_form.cleaned_data["email"]
            password=user_form.cleaned_data["password"]
            if User.objects.filter(username=username).exists():
                messages.error(request, "A user with that username already exists.")
                return redirect('/')
            elif User.objects.filter(email=email).exists():
                messages.error(request, "A user with that email address already exists.")
                return redirect('/')
            else:
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password)
                user.profile.role = profile_form.cleaned_data["role"]
                user.profile.matric_number= profile_form.cleaned_data["matric_number"]
                user.save()
                login(request, user)
                messages.success(request, 'User was successfully created.')
                return redirect('/dashboard')
        for error in user_form.errors.values() or  error in profile_form.errors.values():
            messages.error(request, error)
    login_form = forms.LoginForm()
    context = {
        "user_form": user_form,
        "profile_form": profile_form,
        "login": login_form
    }
    return render(request, "ams_app/auth.html", context=context)


def login_user(request):
    login_form = forms.LoginForm(request.POST or None)
    if request.method == "POST":
        if login_form.is_valid():
            username = login_form.cleaned_data["username"]
            password = login_form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'User was successfully logged in.')
                return redirect('/dashboard')
            else:
                messages.error(request, 'Username or password is incorrect')
                return redirect('/')
        else:
            for error in login_form.errors.values():
                messages.error(request, error)
            return redirect('/')
    context = {
        "login": login_form
    }
    return render(request, "ams_app/auth.html", context=context)


@login_required
def logout_user(request):
    logout(request)
    return redirect('/')


@login_required
def dashboard(request):
    assignment_form = forms.AssignmentForm(request.POST or None)
    search_form = forms.AssignmentSearchForm(request.GET or None)
    user_id = request.user.id
    user = request.user.profile
    assignments = request.user.assignments.all()
    assignments_list = assignments
    if user.role == 'Lecturer':
        paginator = Paginator(assignments_list, 10)
        page = request.GET.get('page')
        try:
            assignments_list = paginator.page(page)
        except PageNotAnInteger:
            assignments_list = paginator.page(1)
        except EmptyPage:
            assignments_list = paginator.page(paginator.num_pages)

        if request.method == 'GET':
            if search_form.is_valid():
                q = request.GET['q']
                assignments = assignments.annotate(
                    search=SearchVector('title', 'course_code', 'course_title'),
                    ).filter(search=SearchQuery(q))

                paginator = Paginator(assignments, 10)
                page = request.GET.get('page')
                try:
                    assignments = paginator.page(page)
                except PageNotAnInteger:
                    assignments = paginator.page(1)
                except EmptyPage:
                    assignments = paginator.page(paginator.num_pages)
            else:
                for error in search_form.errors.values():
                    messages(request, error)
                    
                context = {
                    "assignments": assignments,
                    "search_form": search_form,
                    "assignment": assignment_form
                }
                return render(request, 'ams_app/dashboard.html', context=context)
        context = {
            "assignments": assignments,
            "assignment": assignment_form,
            "search_form": search_form
        }
        return render(request, 'ams_app/dashboard.html', context=context)
    else:
        submissions = request.user.submissions.all()
        submissions_list = submissions
        search_form = forms.SubmissionSearchForm(request.GET or None)
        paginator = Paginator(submissions_list, 10)
        page = request.GET.get('page')
        try:
            submissions_list = paginator.page(page)
        except PageNotAnInteger:
            submissions_list = paginator.page(1)
        except EmptyPage:
            submissions_list = paginator.page(paginator.num_pages)

        if request.method == 'GET':
            if search_form.is_valid():
                q = request.GET['q']
                submissions = submissions.annotate(
                    search=SearchVector('matric_number'),
                    ).filter(search=SearchQuery(q))

                paginator = Paginator(submissions, 10)
                page = request.GET.get('page')
                try:
                    submissions = paginator.page(page)
                except PageNotAnInteger:
                    submissions = paginator.page(1)
                except EmptyPage:
                    submissions = paginator.page(paginator.num_pages)

                context = {
                    "search_form": search_form,
                    "submissions": submissions
                    }
                return render(request, 'ams_app/students_dashboard.html', context=context)
        context = {
            "search_form": search_form,
            "submissions": submissions,
        }
        return render(request, 'ams_app/students_dashboard.html', context=context)

             
@login_required
def create_assignment(request):
    assignment_form = forms.AssignmentForm(request.POST or None)
    if request.user.profile.role == 'Lecturer':
        if request.method == "POST":
            if assignment_form.is_valid():
                assignment = assignment_form.save(commit=False)
                assignment.user_id = request.user.id
                assignment.save()
                new_data = Assignment.objects.last()
                messages.success(request, 'Assignment was successfully created.')
                return redirect('/dashboard')
            else:
                for error in assignment_form.errors.values():
                    messages.error(request, error)
        context = {
            "assignment": assignment_form
        }
        return render(request, "ams_app/dashboard.html", context=context)
    else:
        messages.error(request, 'Only Lecturer accounts can create assignments')
        context = {
            "assignment": assignment_form
        }
        return render(request, "ams_app/dashboard.html", context=context)


@login_required
def assignment_detail(request, id):
    assignment = Assignment.objects.get(id=id)
    initial = {
        "title": assignment.title,
        "upload": assignment.upload,
        "due_date": assignment.due_date,
        "course_code": assignment.course_code,
        "course_title": assignment.course_title
        }
    assignment_form = forms.AssignmentForm(initial=initial)
    context = {
        "single_assignment": assignment,
        "assignment_id": id,
        "assignment": assignment_form
    }
    return render(request, 'ams_app/assignment-detail.html', context=context)


@login_required
def assignment_submissions(request, id):
    assignment_id = id
    if request.user.profile.role == 'Lecturer':
        search_form = forms.SubmissionSearchForm(request.GET or None)
        feedback_form = forms.FeedbackForm(request.POST or None)
        grade_form = forms.GradeForm(request.POST or None)
        assignment = Assignment.objects.get(id=id)
        submissions = assignment.submissions.all().order_by('matric_number')
        submissions_list = submissions
        paginator = Paginator(submissions_list, 10)
        page = request.GET.get('page')
        try:
            submissions_list = paginator.page(page)
        except PageNotAnInteger:
            submissions_list = paginator.page(1)
        except EmptyPage:
            submissions_list = paginator.page(paginator.num_pages)

        if request.method == 'POST':
            if feedback_form.is_valid():
                feedback = request.POST['feedback']
                submission_id = request.POST['submit-feedback']
                submission = Submission.objects.get(id=submission_id)
                submission.feedback = feedback
                submission.save()
            elif grade_form.is_valid():
                grade = request.POST['grade']
                submission_id = request.POST['submit-grade']
                submission = Submission.objects.get(id=submission_id)
                submission.grade = grade
                submission.save()

        if request.method == "GET":

ams_app/templates/ams_app/assignment-detail.html
{% extends "ams_app/base.html" %}
{% block title %}Assignment Management System{% endblock %}
{% block content%}

<div class="container assignment-detail">
  <div class="row single-assignment">
    <div class="col s12">
      <h4> {{ single_assignment.title }} </h4> </div>
    <div class="col s12">
       <p> Upload: <a href="{{ single_assignment.upload.url }}"> {{ single_assignment.upload }}  </a> </p> </div>
    <div class="col s12">
      <p> Due Date: {{ single_assignment.due_date }} </p> </div>
    <div class="col s12">
      <p> Course Code: {{ single_assignment.course_code }} </p> </div>
    <div class="col s12">
      <p> Course Title: {{ single_assignment.course_title }} <p> </div>
    <div class="col s12">
      <p> Passcode: {{ single_assignment.passcode }} </p> </div>
  </div>
  <form method="POST" action={% url 'delete_assignment' id=assignment_id %}>
    {% csrf_token %}
    <div class="edit-delete">
      <a class="waves-effect waves-light btn modal-trigger" href="#modal1"><i class="material-icons right">edit</i>Edit</a>
      <button class="btn waves-effect waves-light btn-delete" type="submit" name="delete-assignment">Delete
        <i class="material-icons right">delete</i>
      </button>
    </div>
  </form>
   <div>
    <script>
      {% if messages %}
          {% for message in messages %}
            {% if message.tags %}
              {% if message.tags == "error" %}
                Materialize.toast('{{ message }}', 2000, 'red');
              {% else %}
                Materialize.toast('{{ message }}', 2000, 'green');
              {% endif %}
            {% endif %}
          {% endfor %}
      {% endif %}
    </script>
  </div>
</div>
<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content assignment-edit">
      <h4>Edit Assignment</h4>
      <div class="edit-modal">
        <div class="modal-container">
          <form method="POST" action="{% url 'edit_assignment' id=assignment_id %}" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="row">
                  <div class="input-field col s12">
                    {{ assignment.title }}
                    <label for="id_title">Title</label>
                  </div>
                  <div class="input-field col s12">
                    {{ assignment.course_title }}
                    <label for="id_course_title">Course title</label>
                  </div>
                  <div class="input-field col s12">
                    {{ assignment.course_code }}
                    <label for="id_course_code">Course code</label>
                  </div>
                  <div class="col s12">
                    {{ assignment.due_date }}
                  </div>
                </div>
                <div class="row">
                  <div class="file-field input-field col s12">
                    <div class="btn col s6">
                      <span>File</span>
                      {{ assignment.upload }}
                    </div>
                    <div class="file-path-wrapper col s6">
                      <input class="file-path validate" type="text" placeholder="Upload one or more files">
                    </div>
                  </div>
                </div>
                <button class="btn waves-effect waves-light modal-action modal-close" type="submit" name="edit-assignment">Edit assignment
                  <i class="material-icons right">send</i>
                </button>
              </form>
            </div>
          <div>
          <script>
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags %}
                    {% if message.tags == "error" %}
                      Materialize.toast('{{ message }}', 2000, 'red');
                    {% else %}
                      Materialize.toast('{{ message }}', 2000, 'green');
                    {% endif %}
                  {% endif %}
                {% endfor %}
            {% endif %}
          </script>
        </div>
      </div>
    </div>

{% endblock %}

ams_app/templates/ams_app/assignment-submissions.html
{% extends "ams_app/base.html" %}
{% block title %}Assignment Management System{% endblock %}
{% block content%}

<div>
  {% if submissions %}
    <div class="body">
      <div class="sub-body">
        <div class="row">
          <form method="GET">
            <div class="input-field col s8 offset-s2 input-search">
              <i class="material-icons right">search</i>
              {{ search_form }}
            </div>
          </form>
        </div>
        <div class="no-assignment">
           <table class="striped responsive-table table">
            <thead>
              <tr>
                  <th>#</th>
                  <th>Matriculation number</th>
                  <th>Upload</th>
                  <th>Date submitted</th>
                  <th>Grade</th>
                  <th>Feedback</th>
              </tr>
            </thead>

            <tbody>
                {% for submission in submissions %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ submission.matric_number }}</td>
                  <td>{{ submission.upload }}</td>
                  <td>{{ submission.submitted_at }}</td>
                  <td>
                    {% if submission.grade != 'No grade yet' %}
                      {{ submission.grade }}
                    {% else %}
                      <a class="modal-trigger" href="#modal-{{ submission.id }}">Grade</a>
                      <!-- {{ grade_form }} -->
                    {% endif %}
                  </td>
                  <td>
                    {% if submission.feedback != 'No feedback yet' %}
                      {{ submission.feedback }}
                    {% else %}
                      <form method="POST" enctype="multipart/form-data" class="feedback-form">
                        {% csrf_token %}
                        {{ feedback_form.feedback }}
                        <button type="submit" name="submit-feedback" value="{{ submission.id }}">
                          <i class="material-icons">send</i>
                        </button>
                      </form>
                      </td>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
          </table>
        </div>
        <div class="pagination-div">
          <ul class="pagination">
            {% if submissions.has_previous %}
              <li class="waves-effect"><a href="?page={{ submissions.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            {% else %}
              <li class="disabled"><span><i class="material-icons">chevron_left</i></span></li>
            {% endif %}
            {% for i in submissions.paginator.page_range %}
              {% if submissions.number == i %}
                <li class=" waves-effect active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if submissions.has_next %}
              <li class="waves-effect"><a href="?page={{ submissions.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% else %}
              <li class="disabled"><span><i class="material-icons">chevron_right</i></span></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    {% for submission in submissions %}
      <!-- Modal Structure -->
      <div id="modal-{{ submission.id }}" class="modal">
        <div class="modal-content">
          <h4>Grade Submission</h4>
          <form method="POST" enctype="multipart/form-data" class="feedback-form">
            {% csrf_token %}
            {{ grade_form.grade }}
            <button type="submit" name="submit-grade" value="{{ submission.id }}">
              <i class="material-icons">send</i>
            </button>
          </form>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="body">
      <div class="sub-body">
        <div class="no-assignment">
          <p> No submissions yet </p>
        </div>
      </div>
    </div>
  {% endif %}
           
</div>

{% endblock %}

ams_app/templates/ams_app/dashboard.html
{% extends "ams_app/base.html" %}
{% block title %}Assignment Management System{% endblock %}
{% block content%}
{% block assignments %}{% endblock %}

{% if assignments %}
  <div class="body">
    <div class="sub-body">
      <div class="row search-row">
        <form method="GET">
          <div class="input-field col s8 input-search offset-s2">
            <i class="material-icons right">search</i>
            {{ search_form }}
          </div>
        </form>
      </div>
      <div class="no-assignment">
          <table class="striped responsive-table table">
          <thead>
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Upload</th>
                <th>Date Created</th>
                <th>Due date</th>
                <th>Course code</th>
                <th>Course title</th>
                <th>Submissions</th>
            </tr>
          </thead>

          <tbody>
            {% for assignment in assignments %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/assignments/{{ assignment.id }}">{{ assignment.title }}</a></td>
                <td>{{ assignment.upload }}</td>
                <td>{{ assignment.created_at }}</td>
                <td>{{ assignment.due_date }}</td>
                <td>{{ assignment.course_code }}</td>
                <td>{{ assignment.course_title }}</td>
                <td><a href="/assignments/{{ assignment.id }}/submissions">{{ assignment.submissions.count }}</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col s2">
        <a class="btn-floating btn-large waves-effect waves-light add-assignment modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
      </div>
      <div class="pagination-div">
        {% if assignments.has_other_pages %}
          <ul class="pagination">
            {% if assignments.has_previous %}
              <li class="waves-effect"><a href="?page={{ assignments.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            {% else %}
              <li class="disabled"><span><i class="material-icons">chevron_left</i></span></li>
            {% endif %}
            {% for i in assignments.paginator.page_range %}
              {% if assignments.number == i %}
                <li class=" waves-effect active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if assignments.has_next %}
              <li class="waves-effect"><a href="?page={{ assignments.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% else %}
              <li class="disabled"><span><i class="material-icons">chevron_right</i></span></li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
  </div>
  <div>

{% else %}
  <div class="body">
    <div class="sub-body">
      <div class="row">
        <div class="col s2">
          <a class="btn-floating btn-large waves-effect waves-light add-assignment modal-trigger" href="#modal1"><i class="material-icons">add</i></a>
        </div>
      <div class="no-assignment">
        <p> No assignment created yet </p>
      </div>
    </div>
  </div>
{% endif %}

<!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Create Assignment</h4>
      <div>
        <div class="modal-container">
          <form method="POST" action={% url 'add_assignment'%} enctype="multipart/form-data">
            {% csrf_token %}
                <div class="row">
                  <div class="input-field col s12">
                    {{ assignment.title }}
                    <label for="id_title">Title</label>
                  </div>
                  <div class="input-field col s12">
                    {{ assignment.course_title }}
                    <label for="id_course_title">Course title</label>
                  </div>
                  <div class="input-field col s12">
                    {{ assignment.course_code }}
                    <label for="id_course_code">Course code</label>
                  </div>
                  <div class="col s12">
                    {{ assignment.due_date }}
                  </div>
                </div>
                <div class="row">
                  <div class="file-field input-field col s12">
                    <div class="btn col s6">
                      <span>File</span>
                      {{ assignment.upload }}
                    </div>
                    <div class="file-path-wrapper col s6">
                      <input class="file-path validate" type="text" placeholder="Upload one or more files">
                    </div>
                  </div>
                </div>
                <button class="btn waves-effect waves-light modal-action modal-close" type="submit" name="create-assignment">Create assignment
                  <i class="material-icons right">send</i>
                </button>
              </form>
            </div>
          <div>
          <script>
            {% if messages %}
                {% for message in messages %}
                  {% if message.tags %}
                    {% if message.tags == "error" %}
                      Materialize.toast('{{ message }}', 2000, 'red');
                    {% else %}
                      Materialize.toast('{{ message }}', 2000, 'green');
                    {% endif %}
                  {% endif %}
                {% endfor %}
            {% endif %}
          </script>
        </div>
      </div>
    </div>

{% endblock %}

ams_app/templates/ams_app/pass.html
{% extends "ams_app/base.html" %}
{% block title %}Assignment Management System{% endblock %}
{% block content%}
<div class="container assignment-pass">
  <div>
    <h4> Enter the Assignment Passcode</h4>
  </div>
  <form method="POST" action={% url 'pre_submission' id=assignment_id%}>
    {% csrf_token %}
    <div class="row pass-row">
      <div class="input-field col s12 input-pass">
        {{ pass }}
      </div>
      <div class="col s12">
        <button class="btn waves-effect waves-light" type="submit" name="pass">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  </form>
</div>
<div>
  <script>
    {% if messages %}
        {% for message in messages %}
          {% if message.tags %}
            {% if message.tags == "error" %}
              Materialize.toast('{{ message }}', 2000, 'red');
            {% else %}
              Materialize.toast('{{ message }}', 2000, 'green');
            {% endif %}
          {% endif %}
        {% endfor %}
    {% endif %}
  </script>
</div>
{% endblock %}